task1

In [43]:
import numpy as np

In [44]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [45]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
a2 = a.reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
a3 = a.reshape(12,1)
a3

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [48]:
a4 = a.reshape(4,3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [49]:
a5 = a.reshape(6,2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [50]:
b1 = a.reshape(-1, 12)
b1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [51]:
b2 = a.reshape(12, -1)
b2

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [52]:
b3 = a.reshape(4, -1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [53]:
b4 = a.reshape(-1, 4)
b4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
b5 = a.reshape(-1, 6)
b5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [55]:
mt = np.random.randn(3,4)
mt

array([[-0.68714697,  1.19206844, -0.84700524,  1.07257526],
       [ 1.02824282,  0.16636136, -0.69212473, -2.43031536],
       [ 0.45739422,  0.62461971, -0.30070124, -2.21484059]])

In [56]:
mt_f = mt.flatten()
mt_f

array([-0.68714697,  1.19206844, -0.84700524,  1.07257526,  1.02824282,
        0.16636136, -0.69212473, -2.43031536,  0.45739422,  0.62461971,
       -0.30070124, -2.21484059])

In [57]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [58]:
b = np.arange(20, 1,-2)
b = b.reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [59]:
### у данных массивов один размер , но разная форма  
a.shape == b.shape

False

In [60]:
a.size == b.size

True

In [61]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [62]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [64]:
v.size

10

In [65]:
A = np.arange(0,12)
A = A.reshape(4,3)
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [66]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [67]:
B.size

16

In [68]:
### linalg.LinAlgError - исключение, вызываемое данными функциями в случае неудачи 
###(например, при попытке взять обратную матрицу от вырожденной).
np.linalg.inv(B)

LinAlgError: Singular matrix

In [69]:
np.random.seed(42)

In [70]:
c = np.arange(0,16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
C = c.reshape(4,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
D = np.add(B, np.dot(C,10))
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [73]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 1.10382344e+13,  5.26315789e-02, -3.31147031e+13,
         2.20764688e+13],
       [-8.46264636e+13,  9.38249922e+13,  6.62294063e+13,
        -7.54279349e+13],
       [ 1.36138224e+14, -1.87649984e+14, -3.31147031e+13,
         8.46264636e+13],
       [-6.25499948e+13,  9.38249922e+13,  0.00000000e+00,
        -3.12749974e+13]])

In [74]:
np.linalg.det(D)

-7.685903354004529e-25

In [75]:
np.linalg.matrix_rank(D)

2

In [23]:
b3 = a.reshape(4, -1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [84]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [88]:
E = np.where(D_inv, B, C)
E 

array([[  5,  14,   2,  32],
       [  4,  50,  86,   7],
       [ 23,   9,  10, 212],
       [ 12, 122,  14,  15]])

In [94]:
B == E 

array([[ True,  True, False,  True],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [False,  True, False, False]])

In [92]:
C == E

array([[False, False,  True, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True]])

Task2

In [77]:
a = np.array([1, 6, 2, 8, 3, 11, 3, 10, 1, 7])
a = a.reshape(5,2)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
mean_a = np.mean(a, axis=0)
mean_a

Task3

In [ ]:
a_centered = a - mean_a
a_centered

Task4

In [ ]:
ar = a_centered.T
ar1 = ar[0]
ar2 = ar[1]
a_centered_sp = np.dot(ar1, ar2)
a_centered_sp

In [ ]:
an = a_centered_sp / ((a.size/2)-1)
an

#### Task5


In [ ]:
a_cov = np.cov(a.T)
a_cov

In [ ]:
a_cov == an